---
driver:
  name: docker
  use_sudo: false

provisioner:
  name: chef_zero
  require_chef_omnibus: 11.10.4

platforms:
  - name: centos
    driver_config:
      image: centos:6

suites:
  - name: default
    run_list:
      - recipe[tornado::default]
    attributes: {}
