name             'tornado'
maintainer       'DataSift'
maintainer_email 'operations@datasift.com'
license          'All rights reserved'
description      'Installs/Configures tornado'
long_description 'Installs/Configures tornado'
version          '0.1.0'
depends          'php'
depends          'php-fpm'
depends          'supervisor'
depends          'nginx'
depends          'memcached'
