-- MySQL Script generated by MySQL Workbench
-- Fri Nov 20 23:23:47 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema tornado
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tornado
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tornado` DEFAULT CHARACTER SET ascii COLLATE ascii_bin ;
USE `tornado` ;

-- -----------------------------------------------------
-- Table `tornado`.`organization`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tornado`.`organization` ;

CREATE TABLE IF NOT EXISTS `tornado`.`organization` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `skin` VARCHAR(255) NULL,
  `jwt_secret` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = ascii
COLLATE = ascii_bin;


-- -----------------------------------------------------
-- Table `tornado`.`agency`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tornado`.`agency` ;

CREATE TABLE IF NOT EXISTS `tornado`.`agency` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `organization_id` INT UNSIGNED NOT NULL,
  `name` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `datasift_username` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `datasift_apikey` VARCHAR(45) NULL DEFAULT NULL,
  `skin` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_agency_organization_1`
    FOREIGN KEY (`organization_id`)
    REFERENCES `tornado`.`organization` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = ascii
COLLATE = ascii_bin;

CREATE INDEX `fk_agency_organization_1_idx` ON `tornado`.`agency` (`organization_id` ASC);

CREATE UNIQUE INDEX `unique_agency_ds_username` ON `tornado`.`agency` (`datasift_username` ASC);

CREATE UNIQUE INDEX `unique_agency_ds_apikey` ON `tornado`.`agency` (`datasift_apikey` ASC);


-- -----------------------------------------------------
-- Table `tornado`.`brand`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tornado`.`brand` ;

CREATE TABLE IF NOT EXISTS `tornado`.`brand` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `agency_id` INT UNSIGNED NOT NULL,
  `name` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `datasift_identity_id` VARCHAR(45) NULL DEFAULT NULL,
  `datasift_apikey` VARCHAR(45) NULL DEFAULT NULL,
  `target_permissions` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_brand_agency_1`
    FOREIGN KEY (`agency_id`)
    REFERENCES `tornado`.`agency` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = ascii
COLLATE = ascii_bin;

CREATE INDEX `fk_brand_agency_1_idx` ON `tornado`.`brand` (`agency_id` ASC);

CREATE UNIQUE INDEX `unique_brand_ds_indetity` ON `tornado`.`brand` (`datasift_identity_id` ASC);

CREATE UNIQUE INDEX `unique_brand_ds_apikey` ON `tornado`.`brand` (`datasift_apikey` ASC);


-- -----------------------------------------------------
-- Table `tornado`.`project`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tornado`.`project` ;

CREATE TABLE IF NOT EXISTS `tornado`.`project` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `brand_id` INT UNSIGNED NOT NULL,
  `name` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `type` TINYINT NOT NULL DEFAULT 0,
  `recording_filter` TINYINT NULL DEFAULT NULL,
  `fresh` TINYINT(1) NOT NULL DEFAULT 1,
  `created_at` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_project_brand1`
    FOREIGN KEY (`brand_id`)
    REFERENCES `tornado`.`brand` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = ascii
COLLATE = ascii_bin;

CREATE UNIQUE INDEX `unique_project_brand_idx` ON `tornado`.`project` (`brand_id` ASC, `name` ASC);


-- -----------------------------------------------------
-- Table `tornado`.`recording`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tornado`.`recording` ;

CREATE TABLE IF NOT EXISTS `tornado`.`recording` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `brand_id` INT UNSIGNED NOT NULL,
  `project_id` INT UNSIGNED NULL,
  `datasift_recording_id` VARCHAR(255) NOT NULL,
  `hash` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `status` VARCHAR(10) NOT NULL DEFAULT 'started',
  `csdl` LONGTEXT NULL DEFAULT NULL,
  `vqb_generated` TINYINT UNSIGNED NOT NULL,
  `created_at` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_recording_brand1`
    FOREIGN KEY (`brand_id`)
    REFERENCES `tornado`.`brand` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_recording_project1`
    FOREIGN KEY (`project_id`)
    REFERENCES `tornado`.`project` (`id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = ascii
COLLATE = ascii_bin;

CREATE INDEX `fk_recording_brand1_idx` ON `tornado`.`recording` (`brand_id` ASC);

CREATE INDEX `fk_recording_project1_idx` ON `tornado`.`recording` (`project_id` ASC);


-- -----------------------------------------------------
-- Table `tornado`.`dataset`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tornado`.`dataset` ;

CREATE TABLE IF NOT EXISTS `tornado`.`dataset` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `dimensions` VARCHAR(255) NOT NULL,
  `visibility` VARCHAR(20) NOT NULL,
  `data` LONGTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = ascii
COLLATE = ascii_bin;


-- -----------------------------------------------------
-- Table `tornado`.`workbook`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tornado`.`workbook` ;

CREATE TABLE IF NOT EXISTS `tornado`.`workbook` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `project_id` INT UNSIGNED NULL DEFAULT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `recording_id` INT UNSIGNED NULL DEFAULT NULL,
  `rank` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_workbook_project`
    FOREIGN KEY (`project_id`)
    REFERENCES `tornado`.`project` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_workbook_recording`
    FOREIGN KEY (`recording_id`)
    REFERENCES `tornado`.`recording` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_workbook_project_idx` ON `tornado`.`workbook` (`project_id` ASC);

CREATE INDEX `fk_workbook_recording_idx` ON `tornado`.`workbook` (`recording_id` ASC);


-- -----------------------------------------------------
-- Table `tornado`.`worksheet`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tornado`.`worksheet` ;

CREATE TABLE IF NOT EXISTS `tornado`.`worksheet` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `workbook_id` INT UNSIGNED NOT NULL,
  `name` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `rank` INT UNSIGNED NOT NULL,
  `comparison` VARCHAR(10) NOT NULL DEFAULT 'baseline',
  `measurement` VARCHAR(15) NOT NULL DEFAULT 'unique_authors',
  `chart_type` VARCHAR(10) NOT NULL DEFAULT 'tornado',
  `analysis_type` VARCHAR(10) NOT NULL DEFAULT 'freqDist',
  `secondary_recording_id` INT UNSIGNED NULL DEFAULT NULL,
  `secondary_recording_filters` BLOB NULL DEFAULT NULL,
  `baseline_dataset_id` INT UNSIGNED NULL DEFAULT NULL,
  `parent_worksheet_id` INT NULL DEFAULT NULL,
  `filters` BLOB NULL DEFAULT NULL,
  `dimensions` BLOB NULL DEFAULT NULL,
  `start` INT NULL DEFAULT NULL,
  `end` INT NULL DEFAULT NULL,
  `created_at` INT NULL DEFAULT NULL,
  `updated_at` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_worksheet_recording2`
    FOREIGN KEY (`secondary_recording_id`)
    REFERENCES `tornado`.`recording` (`id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_worksheet_dataset1`
    FOREIGN KEY (`baseline_dataset_id`)
    REFERENCES `tornado`.`dataset` (`id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_parent_worksheet`
    FOREIGN KEY (`parent_worksheet_id`)
    REFERENCES `tornado`.`worksheet` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_worksheet_workbook`
    FOREIGN KEY (`workbook_id`)
    REFERENCES `tornado`.`workbook` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = ascii
COLLATE = ascii_bin;

CREATE UNIQUE INDEX `unique_name_workbook_id` ON `tornado`.`worksheet` (`workbook_id` ASC, `name` ASC);

CREATE INDEX `fk_worksheet_recording2_idx` ON `tornado`.`worksheet` (`secondary_recording_id` ASC);

CREATE INDEX `fk_worksheet_dataset1_idx` ON `tornado`.`worksheet` (`baseline_dataset_id` ASC);

CREATE INDEX `fk_worksheet_workbook_idx` ON `tornado`.`worksheet` (`workbook_id` ASC);

CREATE INDEX `fk_worksheet_worksheet1_idx` ON `tornado`.`worksheet` (`parent_worksheet_id` ASC);


-- -----------------------------------------------------
-- Table `tornado`.`chart`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tornado`.`chart` ;

CREATE TABLE IF NOT EXISTS `tornado`.`chart` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `worksheet_id` INT NOT NULL,
  `name` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `rank` INT UNSIGNED NOT NULL,
  `type` VARCHAR(20) NOT NULL,
  `data` BLOB NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_chart_worksheet1`
    FOREIGN KEY (`worksheet_id`)
    REFERENCES `tornado`.`worksheet` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = ascii
COLLATE = ascii_bin;

CREATE INDEX `fk_chart_worksheet1_idx` ON `tornado`.`chart` (`worksheet_id` ASC);


-- -----------------------------------------------------
-- Table `tornado`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tornado`.`user` ;

CREATE TABLE IF NOT EXISTS `tornado`.`user` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `organization_id` INT UNSIGNED NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `username` VARCHAR(255) NOT NULL,
  `type` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_user_organization1`
    FOREIGN KEY (`organization_id`)
    REFERENCES `tornado`.`organization` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_user_organization1_idx` ON `tornado`.`user` (`organization_id` ASC);

CREATE UNIQUE INDEX `unique_key_email_org` ON `tornado`.`user` (`organization_id` ASC, `email` ASC);


-- -----------------------------------------------------
-- Table `tornado`.`users_brands`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tornado`.`users_brands` ;

CREATE TABLE IF NOT EXISTS `tornado`.`users_brands` (
  `user_id` INT UNSIGNED NOT NULL,
  `brand_id` INT UNSIGNED NOT NULL,
  CONSTRAINT `fk_table1_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `tornado`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_projects_brand1`
    FOREIGN KEY (`brand_id`)
    REFERENCES `tornado`.`brand` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_table1_user1_idx` ON `tornado`.`users_brands` (`user_id` ASC);

CREATE INDEX `fk_users_projects_brand1_idx` ON `tornado`.`users_brands` (`brand_id` ASC);

CREATE UNIQUE INDEX `user_brand_unique_idx` ON `tornado`.`users_brands` (`user_id` ASC, `brand_id` ASC);


-- -----------------------------------------------------
-- Table `tornado`.`users_agencies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tornado`.`users_agencies` ;

CREATE TABLE IF NOT EXISTS `tornado`.`users_agencies` (
  `user_id` INT UNSIGNED NOT NULL,
  `agency_id` INT UNSIGNED NOT NULL,
  CONSTRAINT `fk_users_agencies_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `tornado`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_agencies_agency1`
    FOREIGN KEY (`agency_id`)
    REFERENCES `tornado`.`agency` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_users_agencies_user1_idx` ON `tornado`.`users_agencies` (`user_id` ASC);

CREATE INDEX `fk_users_agencies_agency1_idx` ON `tornado`.`users_agencies` (`agency_id` ASC);

CREATE UNIQUE INDEX `user_agency_unique_idx` ON `tornado`.`users_agencies` (`agency_id` ASC, `user_id` ASC);


-- -----------------------------------------------------
-- Table `tornado`.`role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tornado`.`role` ;

CREATE TABLE IF NOT EXISTS `tornado`.`role` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tornado`.`users_roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tornado`.`users_roles` ;

CREATE TABLE IF NOT EXISTS `tornado`.`users_roles` (
  `role_id` INT NOT NULL,
  `user_id` INT UNSIGNED NOT NULL,
  CONSTRAINT `fk_users_roles_role1`
    FOREIGN KEY (`role_id`)
    REFERENCES `tornado`.`role` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_roles_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `tornado`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_users_roles_role1_idx` ON `tornado`.`users_roles` (`role_id` ASC);

CREATE INDEX `fk_users_roles_user1_idx` ON `tornado`.`users_roles` (`user_id` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
