services:
    analyze.analysis.form.create:
        class: Tornado\Analyze\Analysis\Form\Create
        parent: project.worksheet.form

    analyze:
        class: Tornado\Analyze\Analyzer
        arguments:
            - @datasift.pylon
            - @stats

    analyze.dataset.generator:
        class: Tornado\Analyze\DataSet\Generator

    analyze.dataset.repository:
        class: Tornado\Analyze\DataSet\StoredDataSet\DataMapper
        arguments:
            - @doctrine.dbal.connection
            - Tornado\Analyze\DataSet\StoredDataSet
            - "dataset"
            - @analyze.dimension.factory.nouser

    analyze.dataset.form:
        class: Tornado\Analyze\DataSet\StoredDataSet\Form
        arguments:
            - @validator
            - @analyze.dataset.repository
            - @project.recording.repository
            - @pylon.schema.provider
            - @analyze.dimension.factory.nouser

    analyze.dimension.factory:
        class: Tornado\Analyze\Dimension\Factory
        arguments:
            - @pylon.schema.provider

    analyze.dimension.factory.nouser:
        class: Tornado\Analyze\Dimension\Factory
        arguments:
            - @pylon.schema.provider.nouser

    analyze.templated.loader:
        class: DataSift\Loader\Json
        arguments: [%analyzer.templates%]

    analyze.templated:
        class: Tornado\Analyze\TemplatedAnalyzer
        arguments:
            - @analyze.templated.loader
            - @analyze
            - @analyze.dimension.factory
